version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region ${region})
      - REPOSITORY_URI=${ecr_repo_url}
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - docker build -f Dockerfile -t ${image_name} .
      - docker tag ${image_name}:latest $REPOSITORY_URI:v$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - docker push $REPOSITORY_URI:v$CODEBUILD_BUILD_NUMBER
      - echo Writting image definitions file...
      - printf '[{"name":"${task_name}","imageUri":"%s"}]' $REPOSITORY_URI:v$CODEBUILD_BUILD_NUMBER > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
cache:
  paths:
    - "/root/.m2/**/*"
